### PR TITLE
Loosen aiohttp requirement

### PR DESCRIPTION
**Pull request by cdce8p**
A hard pin for `aiohttp` will make life quite difficult for downstream packages like Home Assistant. For every new aiohttp release, we would need to wait for `evohome-async` to be updated first. E.g. version `3.9.0b1` was just releases which is incompatible.

Unless there is a specific feature needed, it's usually best / recommended to only pin a lower bound.

_It would be great if a new release could be made after this PR is merged as this is currently blocking Home Assistant._

### CODE REVIEW

**Comment by zxdavb** [comment]
I copy these from HA (and I think they've already changed/about to change), but this may be better:
```
    "aiohttp>=3.9.0b0; python_version >= '3.12'",
    "aiohttp>=3.8.5; python_version < '3.12'",
```

Is that OK?

**Comment by zxdavb** [comment]
Yep - a stupid mistake.

**Comment by cdce8p** [comment]
> I copy these from HA (and I think they've already changed/about to change)

HA is different as it's an application which **should** pin exact versions. For libraries there really is no need to do that.

> but this may be better:
> 
> ```
>     "aiohttp>=3.9.0b0; python_version >= '3.12'",
>     "aiohttp>=3.8.5; python_version < '3.12'",
> ```
> 
> Is that OK?

It would technically work, but isn't ideal as it would even prevent testing of `3.8.x` on `3.12` if a compatible version is ever released.

**Comment by cdce8p** [comment]
> Yep - a stupid mistake.

Not at all. What you did in `requirements.txt` is likely even required for CI to pass. That's where it's placed correctly.
https://github.com/zxdavb/evohome-async/blob/1ba859c185e8aa82ad16da30b4694a01b467318b/requirements.txt#L3-L4

**Comment by zxdavb** [comment]
OK, will take me a few minutes...

**Comment by zxdavb** [comment]
OK, I have done this instead: https://github.com/home-assistant/core/pull/103534

**Pull request closed without merging**
